`timescale 1ns / 1ps

// =============================================================================
// Module: score_fifo
// Project: Flash-SFU H9-O32
// Description: Circular Buffer FIFO for temporary storage of Score values
//              (S_0~S_31) generated by MAC QK, consumed by Reduction Unit.
//              Supports simultaneous read/write with full/empty guards.
//              Includes fifo_flush for tile-boundary soft reset.
// Pipeline Latency: Combinational read, 1-cycle write
// =============================================================================

module score_fifo #(
    parameter DEPTH = 34,     // Minimum 34 for Row overlap safety
    parameter WIDTH = 16,     // FP16 Score
    // Derived parameters (do not override)
    parameter PTR_W = $clog2(DEPTH),       // Pointer width (bits needed to index 0..DEPTH-1)
    parameter CNT_W = $clog2(DEPTH + 1)    // Count width  (0..DEPTH inclusive)
)(
    input  logic              clk,
    input  logic              rst_n,

    // Soft Reset (tile boundary flush)
    input  logic              fifo_flush,

    // Write Port
    input  logic              wr_en,
    input  logic [WIDTH-1:0]  wr_data,

    // Read Port
    input  logic              rd_en,
    output logic [WIDTH-1:0]  rd_data,

    // Status
    output logic              full,
    output logic              empty,
    output logic [CNT_W-1:0]  count     // Current number of entries
);

    // ─────────────────────────────────────────────────────────────────
    // Internal signals
    // ─────────────────────────────────────────────────────────────────
    logic [WIDTH-1:0]  mem [0:DEPTH-1];          // Circular buffer memory

    logic [PTR_W-1:0]  wr_ptr;
    logic [PTR_W-1:0]  rd_ptr;
    logic [CNT_W-1:0]  cnt;

    // Effective enable (guarded)
    logic wr_valid;
    logic rd_valid;
    assign wr_valid = wr_en && !full;
    assign rd_valid = rd_en && !empty;

    // ─────────────────────────────────────────────────────────────────
    // Write Logic
    // ─────────────────────────────────────────────────────────────────
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_ptr <= {PTR_W{1'b0}};
        end else if (fifo_flush) begin
            wr_ptr <= {PTR_W{1'b0}};
        end else if (wr_valid) begin
            mem[wr_ptr] <= wr_data;
            wr_ptr <= (wr_ptr == PTR_W'(DEPTH - 1)) ? {PTR_W{1'b0}} : wr_ptr + {{(PTR_W-1){1'b0}}, 1'b1};
        end
    end

    // ─────────────────────────────────────────────────────────────────
    // Read Logic (combinational read, pointer update on posedge)
    // ─────────────────────────────────────────────────────────────────
    assign rd_data = mem[rd_ptr];

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            rd_ptr <= {PTR_W{1'b0}};
        end else if (fifo_flush) begin
            rd_ptr <= {PTR_W{1'b0}};
        end else if (rd_valid) begin
            rd_ptr <= (rd_ptr == PTR_W'(DEPTH - 1)) ? {PTR_W{1'b0}} : rd_ptr + {{(PTR_W-1){1'b0}}, 1'b1};
        end
    end

    // ─────────────────────────────────────────────────────────────────
    // Count Logic
    // ─────────────────────────────────────────────────────────────────
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            cnt <= {CNT_W{1'b0}};
        end else if (fifo_flush) begin
            cnt <= {CNT_W{1'b0}};
        end else begin
            case ({wr_valid, rd_valid})
                2'b10:   cnt <= cnt + {{(CNT_W-1){1'b0}}, 1'b1};   // Write only
                2'b01:   cnt <= cnt - {{(CNT_W-1){1'b0}}, 1'b1};   // Read only
                default: cnt <= cnt;  // Simultaneous R/W or no-op: count unchanged
            endcase
        end
    end

    // ─────────────────────────────────────────────────────────────────
    // Status Flags
    // ─────────────────────────────────────────────────────────────────
    assign full  = (cnt == CNT_W'(DEPTH));
    assign empty = (cnt == {CNT_W{1'b0}});
    assign count = cnt;

    // ─────────────────────────────────────────────────────────────────
    // Inter Trace Points (simulation only)
    // ─────────────────────────────────────────────────────────────────
    // synthesis translate_off
    always @(posedge clk) begin
        if (rst_n && !fifo_flush) begin
            if (wr_valid)
                $display("[FIFO_WR] time=%0t | wr_ptr=%0d wr_data=%04h count=%0d",
                         $time, wr_ptr, wr_data, cnt);
            if (rd_valid)
                $display("[FIFO_RD] time=%0t | rd_ptr=%0d rd_data=%04h count=%0d",
                         $time, rd_ptr, rd_data, cnt);
        end
    end
    // synthesis translate_on

endmodule
